# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
	config.vm.synced_folder "shared", "/tmp/shared"
	
	config.vm.define "machineA" do |vmA|
		vmA.vm.hostname = "myVMA.gac.local"
		vmA.vm.network "public_network", ip: "192.168.1.31"
		vmA.vm.provision "shell", path: "setupMachineA.sh"
		
		vmA.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "MachineA"
		end
	end
	
	config.vm.define "machineB" do |vmB|
		vmB.vm.hostname = "myVM2.gac.local"
		vmB.vm.network "public_network", ip: "192.168.1.131"
		vmB.vm.provision "shell", path: "setupMachineB.sh"
		
		vmB.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "MachineB"
		end
	end
end
